### ISSUE TITLE
BUG: sing up issue

### ISSUE THREAD

**Issue by nagamukesh** [hereisSwapnil/ExamTime#104]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

when a new user signs up, it is not directing to the actual application
It is showing a blank page
![image](https://github.com/hereisSwapnil/ExamTime/assets/112798996/5069a4bd-2824-43d3-897c-b07e6fe4d062)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by Chetan-Jalandharia** [comment]
please assign this task to me
