### ISSUE TITLE
Feat: Dark mode feature 

### ISSUE THREAD

**Issue by Jagpreet153** [hereisSwapnil/ExamTime#113]
### Describe the feature

Addition of dark mode for better user experience

### Add ScreenShots

![Screenshot 2024-05-12 201012](https://github.com/hereisSwapnil/ExamTime/assets/119691733/e29c2ca6-4964-4b0f-a90f-7c8baef12aef)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by anshdeep0504** [comment]
Hey, allow me to work on this under GSSOC' 2024
