### ISSUE TITLE
BUG: All navigation link redirect on about#

### ISSUE THREAD

**Issue by dhruv8433** [hereisSwapnil/ExamTime#126]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

All Navigation link redirect on about page 
![image](https://github.com/hereisSwapnil/ExamTime/assets/114583978/719ea920-7270-4e38-8cf0-11bb8a476b0f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by dhruv8433** [comment]
Thank you for providing me oppurnity @hereisSwapnil

**Comment by anshdeep0504** [comment]
Hey, allow me to work on this under GSSOC' 2024
