### ISSUE TITLE
 Feature Proposal: Leaderboard System

### ISSUE THREAD

**Issue by Sahilll15** [hereisSwapnil/ExamTime#13]
Incorporate a leaderboard system into the application to foster user engagement and incentivize participation. The leaderboard will enable users to earn coins by adding notes to the platform. Users will be ranked on the leaderboard based on the number of coins they accumulate through their contributions.

**Comment by Sahilll15** [comment]
assign this to me

**Comment by hereisSwapnil** [comment]
@Sahilll15 Done

**Comment by Sahilll15** [comment]
Thanks for the merge !!!
