### ISSUE TITLE
BUG: Sign up function not working properly

### ISSUE THREAD

**Issue by dhruv8433** [hereisSwapnil/ExamTime#136]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

@hereisSwapnil  
check out this image
![image](https://github.com/hereisSwapnil/ExamTime/assets/114583978/bb7f0c93-8b3e-41bf-9aa4-2dd8f887ff36)

when i provide all creditional still they gave me " some error occure "

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by anshdeep0504** [comment]
https://github.com/akshitagupta15june/Moksh/issues

**Comment by anshdeep0504** [comment]
Hey, allow me to work on this under GSSOC' 2024

**Comment by dhruv8433** [comment]
@hereisSwapnil  Thank you

**Comment by dhruv8433** [comment]
@hereisSwapnil  can you please provide me your backend live url...

**Comment by dhruv8433** [comment]
@hereisSwapnil 
i need help
please check this

**Comment by hereisSwapnil** [comment]
@dhruv8433  You don't need live backend url,
You can get it running locally

**Comment by hereisSwapnil** [comment]
And Also the issue has been fixed, You can work on some other issue
