### ISSUE TITLE
BUG: Dark mode is not working properly

### ISSUE THREAD

**Issue by Apoorva-Rajput** [hereisSwapnil/ExamTime#138]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When a user enables dark mode some of the text on the settings page , it does not appears properly . The font color of these text should be changed .
@hereisSwapnil kindly assign me this issue I can handle this bug .
![Screenshot 2024-05-13 162502](https://github.com/hereisSwapnil/ExamTime/assets/98842014/9dbdf2e3-9fc1-4e4a-bc35-654ed739572d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by DurgaPrasad-R** [comment]
Hello, @hereisSwapnil and @Apoorva-Rajput, I'm new to open source contributions. I would like to work on this issue or help if someone working on it is struck somewhere. I kindly request you to consider this.

**Comment by anshdeep0504** [comment]
https://github.com/akshitagupta15june/Moksh/issues

**Comment by anshdeep0504** [comment]
Hey, allow me to work on this under GSSOC' 2024
