### ISSUE TITLE
BUG: like button not working

### ISSUE THREAD

**Issue by msanchariii** [hereisSwapnil/ExamTime#179]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![Screenshot (957)](https://github.com/hereisSwapnil/ExamTime/assets/113378204/535783f4-544f-4aa7-8737-c77d92c75ae8)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [x] I want to work on this issue

**Comment by ananya76** [comment]
Hi Sir, I would like to work on this issue please assign it to me.
