### ISSUE TITLE
Add a settings page

### ISSUE THREAD

**Issue by mehtakevan** [hereisSwapnil/ExamTime#18]
Settings page will contain the functions like to change the theme, manage account settings, etc.

**Comment by mehtakevan** [comment]
@hereisSwapnil Can you please assign this issue to me. I would like to add the settings page.

**Comment by hereisSwapnil** [comment]
@mehtakevan done

**Comment by anwesha2002** [comment]
@hereisSwapnil 
I am a GSSOC'24 contributor. I would like to work on this . Can you please assign this to me
