### ISSUE TITLE
Doc: Add instructions for contribution through GitHub Desktop in README.md

### ISSUE THREAD

**Issue by samarpitadas** [hereisSwapnil/ExamTime#198]
### Describe the documentation update needed

There is a section of instructions for those who contribute through their PC. But section of instructions for contributions through GitHub desktop is missing. @hereisSwapnil could you assign me this issue so that I can fix it?

### Reason for Update

People who contribute through GitHub desktop would get a clear idea. Many contributors here are newbies and it would help them.

### Proposed Changes

I would add a separate section for instructionsmfor	contribution through GitHub desktop.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by hereisSwapnil** [comment]
@samarpitadas Instead of Readme add it in the contributing.md file

**Comment by samarpitadas** [comment]
> @samarpitadas Instead of Readme add it in the contributing.md file

Sure, thank you.
