### ISSUE TITLE
[Fix] The title of the website

### ISSUE THREAD

**Issue by chaitanyarora** [hereisSwapnil/ExamTime#20]
Curretnly the website shows Vite + React.

**Comment by chaitanyarora** [comment]
Thankyou for assigning me this issue!
On it sir!

**Comment by chaitanyarora** [comment]
Sir i have raise a PR [here](https://github.com/hereisSwapnil/ExamTime/pull/24) is the link to that PR.

**Comment by ira-mane** [comment]
If the issue is not resolved ,Can I work on it ? @hereisSwapnil

**Comment by Aman0413** [comment]
please assign to me.
