### ISSUE TITLE
Isn't showing Password requirements before entering

### ISSUE THREAD

**Issue by sakshiSakshi77** [hereisSwapnil/ExamTime#218]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

describe the issue : 
when password entered it Isn't showing Password requirements before entering 
![Screenshot 2024-05-20 191834](https://github.com/hereisSwapnil/ExamTime/assets/159151706/ccc86169-de71-400c-82dc-8c5cb32e0583)
how to fix this : 
i would like to display the conditions when clicked on password bar 
@hereisSwapnil please assign me this issue under gssoc label 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by TanmayKalra09** [comment]
@hereisSwapnil I am done with the changes, can you please assign me this task?
