### ISSUE TITLE
Feat : Adding profile page

### ISSUE THREAD

**Issue by aryansharma220** [hereisSwapnil/ExamTime#224]
### Describe the feature

We can add a profile page to which we can be redirected on clicking on your profile. Please provide with some information you would like to add on the profile page otherwise I can make a demo page with basic details which can be modified later.

### Add ScreenShots

![image](https://github.com/hereisSwapnil/ExamTime/assets/133234867/e17eeb58-8f07-4d71-85eb-08ae194bc080)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by Dhevamuthu** [comment]
Can u assign me this issue under gssoc 2024

**Comment by rajshivam0432** [comment]
can you assign me this
