### ISSUE TITLE
BUG: Website dosent load 

### ISSUE THREAD

**Issue by AnikethDeb2004** [hereisSwapnil/ExamTime#238]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

**The website doesnt load what kind of project is this , it is full blank with white screen .**
![Screenshot (74)](https://github.com/hereisSwapnil/ExamTime/assets/137791848/5a8bac11-3e1c-4166-924e-a0fe7b8bf7df)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [ ] I want to work on this issue

**Comment by hereisSwapnil** [comment]
@AnikethDeb2004 @AnikethDeb2004 The issue has been already resolved
