### ISSUE TITLE
BUG: Signup button is redirecting to Signin page

### ISSUE THREAD

**Issue by Harshilmalhotra** [hereisSwapnil/ExamTime#262]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

On the login page, when we click on Sign-up it temporarily redirects to Sign Up and within one sec it redirects back to Sign In Page.

![Screenshot 2024-05-30 090022](https://github.com/hereisSwapnil/ExamTime/assets/111488708/1d3aaf18-5410-48b9-b1d3-949667a21e7e)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by aryan-1309** [comment]
Please Assign this to me under GSSOC'24.

**Comment by Sowham-3098** [comment]
Yeah, this issue persists. Please assign this to me.

**Comment by abckhush** [comment]
Can you pls assign me this issue?
