### ISSUE TITLE
Password strength

### ISSUE THREAD

**Issue by agarwalhimanshugaya** [hereisSwapnil/ExamTime#264]
### Describe the feature

In our website any input password by user is accepted and now times password strength is very concern so i want to make the feature so that only strong password is taken by website and when user give simple password then there is suggestion shown to the user 

### Add ScreenShots

No screenshot

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by abckhush** [comment]
Can you pls assign me this issue?

**Comment by TanmayKalra09** [comment]
@hereisSwapnil can you please assign me this issue?

**Comment by malvika-sinha** [comment]
I want to resolve the issue, kindly assign me the task
