### ISSUE TITLE
Adding functionality to like feature to a note

### ISSUE THREAD

**Issue by drockparashar** [hereisSwapnil/ExamTime#37]
![image](https://github.com/hereisSwapnil/ExamTime/assets/118686637/5cc76ee6-0ee1-483e-8f44-2789a5984f0c)

Here, the like button is not working for a note.

**Comment by tusharyadav11** [comment]
I would like to contribute for it under GssoC'24

**Comment by devu007** [comment]
Please assign this issue to me. I want to work upon it.
