### ISSUE TITLE
Adding Sign out functionality

### ISSUE THREAD

**Issue by anwesha2002** [hereisSwapnil/ExamTime#44]
@hereisSwapnil 
The sign out is not working. It is not signing out the user. I am a GSSoc'24 contributor . I would like to work on this issue . Can you please assign this to me.

**Comment by tusharyadav11** [comment]
I want to work on the signout functionality. I would like to work on this issue. If you could assign me i would be very grateful to you .

**Comment by Sooraj002** [comment]
i would like to fix this issue
