### ISSUE TITLE
Problems with Signin/Signout session

### ISSUE THREAD

**Issue by CS251000** [hereisSwapnil/ExamTime#45]
When registering the page should automatically render the login page which is not the case here. Also on clicking Signout there is no response.

Kindly assign me this issue under gssoc24

**Comment by hereisSwapnil** [comment]
@CS251000 Done :+1:

**Comment by CS251000** [comment]
@hereisSwapnil request to put this issue under level 2 og gssoc as along with handling signout sessions There are issues with register and login page and not any smooth transition between the 2 when creating new user.

**Comment by CS251000** [comment]
I have completed the amends in my forked repo
Kindly inform ASAP whether you are putting a level2 tag or not so that i can create a pr

**Comment by hereisSwapnil** [comment]
@CS251000 After signup, please redirect the user to the homepage as the user will be automatically logged in

**Comment by CS251000** [comment]
@hereisSwapnil should i close this issue?
