### ISSUE TITLE
feature: Bookmark notes feature

### ISSUE THREAD

**Issue by Sahilll15** [hereisSwapnil/ExamTime#51]
We're excited to propose the implementation of a new feature called Bookmark Notes on our website, aimed at empowering students to streamline their note-taking experience and enhance their study routines. Bookmark Notes will revolutionize how students interact with their shared notes, providing them with a robust set of tools to mark, organize, and revisit important sections effortlessly

assign this to me

**Comment by hereisSwapnil** [comment]
@Sahilll15  Done :+1:
