### ISSUE TITLE
Bug: Application Showing White Blank Screen After Sign-Up

### ISSUE THREAD

**Issue by EAGLEARCHER** [hereisSwapnil/ExamTime#53]
**Description:**
After signing up for the application, users are encountering a frustrating issue where they are presented with a white blank screen instead of being redirected to the expected destination. Additionally, upon refreshing the page, users are reverted back to the login page, despite successfully providing credentials during the sign-up process.

**Steps to Reproduce:**

1. Sign up for the application using valid credentials.
2. After successful sign-up, observe that the application displays a white blank screen.
3. Attempt to navigate to different pages or perform any actions, but notice no response or redirection.
4. Refresh the page.
5. Observe that the user is redirected back to the login page instead of the expected destination.
6. Log in using the previously provided credentials.

**Expected Behavior:**
After signing up, users should be seamlessly redirected to the application's dashboard or home page.

**Comment by EAGLEARCHER** [comment]
@hereisSwapnil Can you can assign me uder gssoc'24

**Comment by hereisSwapnil** [comment]
@EAGLEARCHER Done :+1:

**Comment by dhairyagothi** [comment]
@hereisSwapnil please assign this to me
