### ISSUE TITLE
Enhancing the thumbnail of the notes

### ISSUE THREAD

**Issue by Swastik19Nit** [hereisSwapnil/ExamTime#61]
Instead of rendering a static image, it us proposed that the first page of the pdf uploaded will be displayed in the thumbnail.

**Comment by hereisSwapnil** [comment]
@Swastik19Nit also store the thumbnail on mongo DB

**Comment by Swastik19Nit** [comment]
@hereisSwapnil ok sir

**Comment by Tapesh-1308** [comment]
@hereisSwapnil Hii, It's been two weeks since this PR was open, I have made the solution and just one step away to push it, just need access from your side. Can you please assign this issue to me?

**Comment by hereisSwapnil** [comment]
@Swastik19Nit Due to inactivity your issue raised has been removed
