### ISSUE TITLE
Fixing Static Likes Count Issue in Notes Card

### ISSUE THREAD

**Issue by shalininukella** [hereisSwapnil/ExamTime#9]
@hereisSwapnil I would like to fix the "likes" feature in the notes card. The likes feature is not working, the likes count is not increasing, it's static.

Please assign this issue to me under GSSoC'24.

**Comment by hereisSwapnil** [comment]
@shalininukella Please complete the previously assigned issue after that you can work on this

**Comment by ujjwalagrawal-1** [comment]
@shalininukella  I would Like to Solve the Likes Count Issue can you please assign it to me

under GSSOC'24

**Comment by praveen-p09** [comment]
@hereisSwapnil Can I work on this issue under GSSoC '24?

**Comment by ronitsharma03** [comment]
Hey @hereisSwapnil , Can you assign this issue to me under GSSOC?

**Comment by ronitsharma03** [comment]
@hereisSwapnil Thanks for assigning !

**Comment by PSTabaswiniSivamorthy** [comment]
Please assign me to work on this issue .

**Comment by ronitsharma03** [comment]
@hereisSwapnil the bug is already fixed. Please check!
