### ISSUE TITLE
[BUG]: subject selection OTHER option

### ISSUE THREAD

**Issue by Ayush-may** [hereisSwapnil/ExamTime#91]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## DEFINE
I can see that there is no **OTHER** option in the subject selection option , 
If any user clicked on other option , only then this **didnt find ur sub** should appear .
It is taking extra space in the form

## screenshots
1.
![image](https://github.com/hereisSwapnil/ExamTime/assets/112775332/3cfe4573-a28e-4c64-843a-4bd6fc8a5266)
2.
![image](https://github.com/hereisSwapnil/ExamTime/assets/112775332/73651a16-7239-46cd-bf2e-447ba43c5442)

assign me this issue under gssoc'24 and add level label to this.
Thank u

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by hereisSwapnil** [comment]
@Ayush-may someone is already working on the Combo box issue
