### ISSUE TITLE
Feat:Add dark/light mode feature

### ISSUE THREAD

**Issue by dwivedishrey** [hereisSwapnil/ExamTime#92]
### Describe the feature

Want to add dark and light mode feature.
Please assign this to me.

### Add ScreenShots

![Screenshot 2024-05-12 105004](https://github.com/hereisSwapnil/ExamTime/assets/97790062/2608a928-ca7e-4355-a58d-6dfe3a166b16)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by hereisSwapnil** [comment]
@dwivedishrey Someone is already working on this issue
