### ISSUE TITLE
BUG: Fluctuating Form Height Due to Constant Username Availability Check

### ISSUE THREAD

**Issue by mukulpythondev** [hereisSwapnil/ExamTime#93]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description
In the current implementation of the signup form, the username field constantly checks for the availability of the entered username. This results in the form height fluctuating continuously as the user types, which leads to a suboptimal user experience.

### Expected Behavior
The form height should remain stable while the user is typing in the username field. It should only adjust when necessary, such as when additional form fields are revealed or when there are errors in the form submission.

### Steps to Reproduce
1. Navigate to the signup page.
2. Start typing in the username field.
3. Observe the continuous fluctuation in the form height as you type.

### Additional Context
This issue adversely affects the usability of the signup form, potentially causing confusion and frustration for users. It's crucial to address this issue to ensure a smoother user experience and improve overall usability.

### Video Demonstration
[Link to Video](https://github.com/hereisSwapnil/ExamTime/assets/134795697/0e57df4d-e669-4b63-b8b0-e1e857a34536)

### Proposed Solution
One possible solution could be to fix the height of the form using Tailwind CSS. By setting a specific height for the form, we can prevent it from fluctuating as the user types in the username field.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by hereisSwapnil** [comment]
@mukulpythondev Assigned :+1:

**Comment by mukulpythondev** [comment]
@hereisSwapnil Thanks start working on it!
